### ISSUE TITLE
mm2: Main window config group layout incorrect

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#214]
When the main window is stretched horizontally, the config groups panel should expand to fill the available space. Currently, a gap appears between the left side controls and the config groups panel.
Tested on OS X.

Less critically, it is possible to shrink the window horizontally until the config groups panel is partially obscured. This should not be allowed. Tested on OS X in the presence of a config group with a long name (which makes the left side controls wider).

**Comment by ChrisWeisiger** [comment]
The former issue is now fixed. The latter issue would require us to derive the minimum size of the config panel from the width of the strings in its entries; the main window in turn derives its own minimum size from the minimum size of all of its components. 

I did some fiddling with the table to try to accomplish this. The calculations for size are reasonably straightforward:

    @Override
    public Dimension getMinimumSize() {
       int width = 0; 
       for (int column = 0; column < getColumnCount(); ++column) {
          int colWidth = 0; 
          for (int row = 0; row < getRowCount(); ++row) {
             TableCellRenderer renderer = getCellRenderer(row, column);
             Component c = renderer.getTableCellRendererComponent(this,
                   getValueAt(row, column), true, true, row, column);
             colWidth = Math.max(colWidth, c.getPreferredSize().width);
          }    
          width += colWidth;
       }    
       Dimension superSize = super.getPreferredSize();
       return new Dimension(Math.max(superSize.width, width),
             superSize.height);
    }

Unfortunately, getting the layout manager to respect this size is rather more difficult.

**Comment by nicost** [comment]
Behavior seems acceptable now.  Re-open or create new issue if still a problem.
